categories: [Convert Formats]
description: Convert GTF files to BED12 format
long_description: Convert GTF files to BED12 format using the UCSC Kent Bioinformatics utiltities
homepage_url: http://genome-source.cse.ucsc.edu/gitweb/?p=kent.git;a=blob;f=src/userApps/README
name: gtftobed12
owner: lparsons
remote_repository_url: https://github.com/lparsons/galaxy_tools/tree/master/tools/gtfToBed12
