categories:
 - Convert Formats
 - Sequence Analysis
 - RNA
 - Visualization
description: an RNA-seq quality control package
homepage_url: http://www-huber.embl.de/users/anders/HTSeq/doc/overview.html
long_description: https://code.google.com/p/rseqc/
name: rseqc
owner: nilesh
remote_repository_url: https://github.com/lparsons/galaxy_tools/tree/master/tools/rseqc
