categories: !!python/tuple [Genomic Interval Operations, SAM, Sequence Analysis, RNA]
description: !!python/unicode 'Count aligned reads (SAM/BAM) that overlap genomic
  features (GFF)'
homepage_url: !!python/unicode 'http://www-huber.embl.de/users/anders/HTSeq/doc/overview.html'
long_description: !!python/unicode "Uses the htseq-count script from the Python HTSeq\
  \ package.\n\nGiven a file with aligned sequencing reads and a list of genomic features,\
  \ count how many reads map to each feature.\n\nA feature is defined as an interval\
  \ (i.e., a range of positions) on a chromosome or a union of such intervals.\n\n\
  In the case of RNA-Seq, the features are typically genes, where each gene is defined\
  \ as the union of all it's exons. One may also consider each exon as a feature,\
  \ e.g., in order to check for alternative splicing. For comparative ChIP-Seq, the\
  \ features might be binding regions from a pre-determined list.\n\n\nProgram: HTSeq\
  \ (Analysing high-throughput sequencing data with Python) \nVersion: 0.5.4p1 \n\n\
  Repository-Maintainer: Lance Parsons\nRepository-Development: https://bitbucket.org/lance_parsons/htseq_count_galaxy_wrapper"
name: !!python/unicode 'htseq_count'
owner: lparsons
remote_repository_url: !!python/unicode 'https://github.com/lparsons/galaxy_tools/tree/master/tools/htseq_count'
