categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles version 1.1.2-806 of ea-utils.
long_description: |

 Command-line tools for processing biological sequencing data. Barcode demultiplexing, adapter trimming, etc.

homepage_url: https://code.google.com/p/ea-utils/
name: package_ea_utils_1_1_2_806
owner: lparsons
remote_repository_url: https://github.com/lparsons/galaxy-tools/tree/master/packages/package_ea_utils_1_1_2_806
type: tool_dependency_definition
