categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles version 2.4 of RSeQC.
long_description: |

  The RSeQC package provides a number of useful modules that can
  comprehensively evaluate high throughput sequence data especially RNA-seq data.
  \"Basic modules\" quickly inspect sequence quality, nucleotide composition bias,
  PCR bias and GC bias, while \"RNA-seq specific modules\" investigate sequencing
  saturation status of both splicing junction detection and expression
  estimation, mapped reads clipping profile, mapped reads distribution, coverage
  uniformity over gene body, reproducibility, strand specificity and splice
  junction annotation.

  http://rseqc.sourceforge.net/
name: package_rseqc_2_4
owner: lparsons
remote_repository_url: https://github.com/lparsons/galaxy-tools/tree/master/packages/package_rseqc_2_4
type: tool_dependency_definition
